/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_internal_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/simulation/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Internal V1 Simulation Turn */
        post: operations["internal_v1_simulation_turn_internal_v1_simulation_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/simulation/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Internal V1 Simulation Assessment */
        post: operations["internal_v1_simulation_assessment_internal_v1_simulation_assessment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Internal V1 Brief */
        post: operations["internal_v1_brief_internal_v1_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answers */
        Answers: {
            /** Answers */
            answers: components["schemas"]["ApplicationAnswer"][];
        };
        /** ApplicationAnswer */
        ApplicationAnswer: {
            /** Fieldid */
            fieldId: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** AssessmentRequest */
        AssessmentRequest: {
            /** Candidateid */
            candidateId: string;
            /** Scenarioid */
            scenarioId: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "text" | "voice";
            /** Turns */
            turns: components["schemas"]["Turn"][];
        };
        /** AssessmentResult */
        AssessmentResult: {
            /** Scores */
            scores: components["schemas"]["DriveScore"][];
            english: components["schemas"]["EnglishMetrics"];
            /** Interviewquestions */
            interviewQuestions: components["schemas"]["InterviewQuestion"][];
            candidateFeedback: components["schemas"]["CandidateFeedback"];
        };
        /** BriefEnglish */
        BriefEnglish: {
            certificate: components["schemas"]["CertificateLevel"] | null;
            /** Writtencefr */
            writtenCefr: string;
            /** Basis */
            basis: string;
        };
        /** BriefFlag */
        BriefFlag: {
            /** Title */
            title: string;
            /** Ask */
            ask: string;
            /** Sources */
            sources: components["schemas"]["Evidence"][];
        };
        /** BriefQuestion */
        BriefQuestion: {
            /**
             * Competency
             * @enum {string}
             */
            competency: "D" | "R" | "I" | "V" | "E";
            /** Question */
            question: string;
            /** Why */
            why: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** BriefRequest */
        BriefRequest: {
            candidate: components["schemas"]["CandidateView"];
        };
        /** BriefResult */
        BriefResult: {
            /** Summary */
            summary: string;
            /** Questions */
            questions: components["schemas"]["BriefQuestion"][];
            /** Flags */
            flags: components["schemas"]["BriefFlag"][];
            /** Clarify */
            clarify: components["schemas"]["BriefTopic"][];
            english: components["schemas"]["BriefEnglish"];
        };
        /** BriefTopic */
        BriefTopic: {
            /** Topic */
            topic: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /**
         * CandidateFeedback
         * @description The only text the candidate reads: no score, no number, no decision wording.
         */
        CandidateFeedback: {
            /** Strengths */
            strengths: string[];
            /** Growth */
            growth: string[];
            /** Nexttime */
            nextTime: string[];
        };
        /** CandidateView */
        CandidateView: {
            /** Candidateid */
            candidateId: string;
            application: components["schemas"]["Answers"];
            test: components["schemas"]["TestAnswers"];
            englishCertificate?: components["schemas"]["EnglishCertificate"] | null;
        };
        /** CertificateLevel */
        CertificateLevel: {
            /** Type */
            type: string;
            /** Score */
            score: string;
            /** Cefr */
            cefr: string;
        };
        /** DirectorDecision */
        DirectorDecision: {
            /** Beat */
            beat: string;
            /** Nextbeat */
            nextBeat: string;
            /** Reason */
            reason: string;
        };
        /** DriveScore */
        DriveScore: {
            /**
             * Competency
             * @enum {string}
             */
            competency: "D" | "R" | "I" | "V" | "E";
            /** Score */
            score: number | null;
            /** Confidence */
            confidence: ("low" | "medium" | "high") | null;
            /** Rationale */
            rationale: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** EnglishCertificate */
        EnglishCertificate: {
            /** Type */
            type: string;
            /** Score */
            score: string;
        };
        /** EnglishMetrics */
        EnglishMetrics: {
            /** Wordsperminute */
            wordsPerMinute: number | null;
            /** Fillerrate */
            fillerRate: number | null;
            /** Meanturnlength */
            meanTurnLength: number | null;
            /** Lexicaldiversity */
            lexicalDiversity: number | null;
            /** Grammarerrorsper100Words */
            grammarErrorsPer100Words: number | null;
            /** Cefrestimate */
            cefrEstimate: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Source
             * @enum {string}
             */
            source: "application_field" | "test_item" | "simulation_turn" | "interview_turn" | "interview_note" | "surprise_answer";
            /** Sourceid */
            sourceId: string;
            /** Quote */
            quote: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** InterviewQuestion */
        InterviewQuestion: {
            /**
             * Competency
             * @enum {string}
             */
            competency: "D" | "R" | "I" | "V" | "E";
            /** Question */
            question: string;
            /** Reason */
            reason: string;
        };
        /** TestAnswer */
        TestAnswer: {
            /** Itemid */
            itemId: string;
            /** Response */
            response: string;
        };
        /** TestAnswers */
        TestAnswers: {
            /** Answers */
            answers: components["schemas"]["TestAnswer"][];
        };
        /** Turn */
        Turn: {
            /** Turnid */
            turnId: string;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "candidate" | "character";
            /** Text */
            text: string;
            /** Startedat */
            startedAt: string;
            /** Endedat */
            endedAt: string;
        };
        /** TurnRequest */
        TurnRequest: {
            /** Scenarioid */
            scenarioId: string;
            /** Turns */
            turns: components["schemas"]["Turn"][];
            state?: components["schemas"]["TurnState"] | null;
        };
        /** TurnResult */
        TurnResult: {
            /** Text */
            text: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "opening" | "in-progress" | "wrapping-up" | "finished";
            /** Ended */
            ended: boolean;
            director: components["schemas"]["DirectorDecision"];
        };
        /** TurnState */
        TurnState: {
            /** Beat */
            beat: string;
            /** Candidateturns */
            candidateTurns: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_internal_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    internal_v1_simulation_turn_internal_v1_simulation_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_v1_simulation_assessment_internal_v1_simulation_assessment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_v1_brief_internal_v1_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
